apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backend-stg

images:
  - name: tantran0411/e-commerce-order-service
    newTag: gha-staging-adcbe9f

resources:
  - ../../base
